title: Pierre-Alexandre Aranega
author: Pierre-Alexandre Aranega
email: pierre-alexandre.aranega@ensae.fr
description: Pierre-Alexandre Aranega - Ã‰tudiant HEC Paris / ENSAE Paris
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: pierre-alexandre-aranega.github.io/

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Pierre-Alexandre Aranega
  tagline: HEC Paris / ENSAE Paris
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    twitter: 
    github:  pierre-alexandre-aranega
    linkedIn: in/pierre-alexandre-aranega
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed